// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerConnection = {
/**
 * Process-local opaque connection id. It is not a credential and changes after reconnect.
 */
id: string,
/**
 * Initialized `clientInfo.name`; no request payloads or authorization material are exposed.
 */
clientName: string | null, requestAttestation: boolean, isCurrent: boolean, };
